In [1]:
# Tokenization of paragraphs/sentences
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Ved\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [2]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [3]:
sentences = nltk.sent_tokenize(paragraph)

In [4]:
print(sentences)

['I have three visions for India.', 'In 3000 years of our history, people from all over \n               the world have come and invaded us, captured our lands, conquered our minds.', 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.', 'Yet we have not done this to any other nation.', 'We have not conquered anyone.', 'We have not grabbed their land, their culture, \n               their history and tried to enforce our way of life on them.', 'Why?', 'Because we respect the freedom of others.That is why my \n               first vision is that of freedom.', 'I believe that India got its first vision of \n               this in 1857, when we started the War of Independence.', 'It is this freedom that\n               we must protect and nurture and build on.', 'If we are not free, no one will respect us.', 'My second vision for India’s development.', 'For 

In [5]:
words = nltk.word_tokenize(paragraph)

In [6]:
print(words)

['I', 'have', 'three', 'visions', 'for', 'India', '.', 'In', '3000', 'years', 'of', 'our', 'history', ',', 'people', 'from', 'all', 'over', 'the', 'world', 'have', 'come', 'and', 'invaded', 'us', ',', 'captured', 'our', 'lands', ',', 'conquered', 'our', 'minds', '.', 'From', 'Alexander', 'onwards', ',', 'the', 'Greeks', ',', 'the', 'Turks', ',', 'the', 'Moguls', ',', 'the', 'Portuguese', ',', 'the', 'British', ',', 'the', 'French', ',', 'the', 'Dutch', ',', 'all', 'of', 'them', 'came', 'and', 'looted', 'us', ',', 'took', 'over', 'what', 'was', 'ours', '.', 'Yet', 'we', 'have', 'not', 'done', 'this', 'to', 'any', 'other', 'nation', '.', 'We', 'have', 'not', 'conquered', 'anyone', '.', 'We', 'have', 'not', 'grabbed', 'their', 'land', ',', 'their', 'culture', ',', 'their', 'history', 'and', 'tried', 'to', 'enforce', 'our', 'way', 'of', 'life', 'on', 'them', '.', 'Why', '?', 'Because', 'we', 'respect', 'the', 'freedom', 'of', 'others.That', 'is', 'why', 'my', 'first', 'vision', 'is', 'that

# Stemming

In [8]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [9]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [10]:
sentences = nltk.sent_tokenize(paragraph)

In [11]:
stemmer = PorterStemmer()

In [12]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ved\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [13]:
# Stemming
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i] = ' '.join(words)  

In [14]:
print(sentences)

['i three vision india .', 'in 3000 year histori , peopl world come invad us , captur land , conquer mind .', 'from alexand onward , greek , turk , mogul , portugues , british , french , dutch , came loot us , took .', 'yet done nation .', 'we conquer anyon .', 'we grab land , cultur , histori tri enforc way life .', 'whi ?', 'becaus respect freedom others.that first vision freedom .', 'i believ india got first vision 1857 , start war independ .', 'it freedom must protect nurtur build .', 'if free , one respect us .', 'my second vision india ’ develop .', 'for fifti year develop nation .', 'it time see develop nation .', 'we among top 5 nation world term gdp .', 'we 10 percent growth rate area .', 'our poverti level fall .', 'our achiev global recognis today .', 'yet lack self-confid see develop nation , self-reli self-assur .', 'isn ’ incorrect ?', 'i third vision .', 'india must stand world .', 'becaus i believ unless india stand world , one respect us .', 'onli strength respect stre

# Lemmatization

In [15]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [21]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [22]:
sentences = nltk.sent_tokenize(paragraph)
lemmatizer = WordNetLemmatizer()

In [23]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Ved\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [24]:
# Lemmatization
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i] = ' '.join(words)  

In [25]:
print(sentences)

['I three vision India .', 'In 3000 year history , people world come invaded u , captured land , conquered mind .', 'From Alexander onwards , Greeks , Turks , Moguls , Portuguese , British , French , Dutch , came looted u , took .', 'Yet done nation .', 'We conquered anyone .', 'We grabbed land , culture , history tried enforce way life .', 'Why ?', 'Because respect freedom others.That first vision freedom .', 'I believe India got first vision 1857 , started War Independence .', 'It freedom must protect nurture build .', 'If free , one respect u .', 'My second vision India ’ development .', 'For fifty year developing nation .', 'It time see developed nation .', 'We among top 5 nation world term GDP .', 'We 10 percent growth rate area .', 'Our poverty level falling .', 'Our achievement globally recognised today .', 'Yet lack self-confidence see developed nation , self-reliant self-assured .', 'Isn ’ incorrect ?', 'I third vision .', 'India must stand world .', 'Because I believe unless 

# Bag of Words

In [26]:
import nltk
# Cleaning the texts
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [27]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [121]:
ps = PorterStemmer()
wordnet=WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [122]:
print(corpus)

['three vision india', 'year histori peopl world come invad us captur land conquer mind', 'alexand onward greek turk mogul portugues british french dutch came loot us took', 'yet done nation', 'conquer anyon', 'grab land cultur histori tri enforc way life', '', 'respect freedom other first vision freedom', 'believ india got first vision start war independ', 'freedom must protect nurtur build', 'free one respect us', 'second vision india develop', 'fifti year develop nation', 'time see develop nation', 'among top nation world term gdp', 'percent growth rate area', 'poverti level fall', 'achiev global recognis today', 'yet lack self confid see develop nation self reliant self assur', 'incorrect', 'third vision', 'india must stand world', 'believ unless india stand world one respect us', 'strength respect strength', 'must strong militari power also econom power', 'must go hand hand', 'good fortun work three great mind', 'dr vikram sarabhai dept', 'space professor satish dhawan succeed dr 

In [123]:
len(corpus)

31

In [124]:
unique_words = []
for sentence in corpus:
    for word in sentence.split():
        if word not in unique_words:
            unique_words.append(word)

In [125]:
len(unique_words)

113

In [126]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()


In [127]:
X.shape

(31, 113)

In [128]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [129]:
cv_labels = cv.get_feature_names_out()
cv_labels

array(['achiev', 'alexand', 'also', 'among', 'anyon', 'area', 'assur',
       'believ', 'brahm', 'british', 'build', 'came', 'captur', 'career',
       'close', 'come', 'confid', 'conquer', 'consid', 'cultur', 'dept',
       'develop', 'dhawan', 'done', 'dr', 'dutch', 'econom', 'enforc',
       'fall', 'father', 'fifti', 'first', 'fortun', 'four', 'free',
       'freedom', 'french', 'gdp', 'global', 'go', 'good', 'got', 'grab',
       'great', 'greek', 'growth', 'hand', 'histori', 'incorrect',
       'independ', 'india', 'invad', 'lack', 'land', 'level', 'life',
       'loot', 'lucki', 'materi', 'mileston', 'militari', 'mind', 'mogul',
       'must', 'nation', 'nuclear', 'nurtur', 'one', 'onward', 'opportun',
       'other', 'peopl', 'percent', 'portugues', 'poverti', 'power',
       'prakash', 'professor', 'protect', 'rate', 'recognis', 'reliant',
       'respect', 'sarabhai', 'satish', 'second', 'see', 'self', 'space',
       'stand', 'start', 'strength', 'strong', 'succeed', 'term',

In [130]:
len(cv_labels)

113

In [70]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [76]:
for i in range(len(X[0])):
    if X[0][i] == 1:
        print(cv_labels[i])

india
three
vision


# TF-IDF

In [78]:
import nltk
# Cleaning the texts
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [85]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [86]:
ps = PorterStemmer()
wordnet=WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [87]:
print(corpus)

['three vision india', 'year history people world come invaded u captured land conquered mind', 'alexander onwards greek turk mogul portuguese british french dutch came looted u took', 'yet done nation', 'conquered anyone', 'grabbed land culture history tried enforce way life', '', 'respect freedom others first vision freedom', 'believe india got first vision started war independence', 'freedom must protect nurture build', 'free one respect u', 'second vision india development', 'fifty year developing nation', 'time see developed nation', 'among top nation world term gdp', 'percent growth rate area', 'poverty level falling', 'achievement globally recognised today', 'yet lack self confidence see developed nation self reliant self assured', 'incorrect', 'third vision', 'india must stand world', 'believe unless india stand world one respect u', 'strength respect strength', 'must strong military power also economic power', 'must go hand hand', 'good fortune worked three great mind', 'dr vi

In [88]:
# Creating the TF-IDF model
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
X = cv.fit_transform(corpus).toarray()

In [89]:
X.shape

(31, 114)

In [90]:
print(X[0])

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.54830459 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.63144608 0.         0.         

In [91]:
cv_labels = cv.get_feature_names_out()
cv_labels

array(['achievement', 'alexander', 'also', 'among', 'anyone', 'area',
       'assured', 'believe', 'brahm', 'british', 'build', 'came',
       'captured', 'career', 'closely', 'come', 'confidence', 'conquered',
       'consider', 'culture', 'dept', 'developed', 'developing',
       'development', 'dhawan', 'done', 'dr', 'dutch', 'economic',
       'enforce', 'falling', 'father', 'fifty', 'first', 'fortune',
       'four', 'free', 'freedom', 'french', 'gdp', 'globally', 'go',
       'good', 'got', 'grabbed', 'great', 'greek', 'growth', 'hand',
       'history', 'incorrect', 'independence', 'india', 'invaded', 'lack',
       'land', 'level', 'life', 'looted', 'lucky', 'material',
       'milestone', 'military', 'mind', 'mogul', 'must', 'nation',
       'nuclear', 'nurture', 'one', 'onwards', 'opportunity', 'others',
       'people', 'percent', 'portuguese', 'poverty', 'power', 'prakash',
       'professor', 'protect', 'rate', 'recognised', 'reliant', 'respect',
       'sarabhai', 'satish

In [93]:
for i in range(len(X[0])):
    if X[0][i] != 0:
        print(cv_labels[i])

india
three
vision


# Word Embedding

In [94]:
from tensorflow.keras.preprocessing.text import one_hot

In [95]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',
     'the glass of milk is made of glass']

In [96]:
### Vocabulary size
voc_size=10000

In [97]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[6911, 8097, 9108, 1053], [6911, 8097, 9108, 963], [6911, 7327, 9108, 9528], [4454, 2947, 7884, 8977, 3707], [4454, 2947, 7884, 8977, 9892], [6339, 6911, 905, 9108, 3987], [244, 5346, 3949, 8977], [6911, 8097, 9108, 1053, 5517, 1808, 9108, 8097]]


Word Embedding Represntation

In [98]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [99]:
import numpy as np

In [100]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6911 8097 9108 1053]
 [   0    0    0    0 6911 8097 9108  963]
 [   0    0    0    0 6911 7327 9108 9528]
 [   0    0    0 4454 2947 7884 8977 3707]
 [   0    0    0 4454 2947 7884 8977 9892]
 [   0    0    0 6339 6911  905 9108 3987]
 [   0    0    0    0  244 5346 3949 8977]
 [6911 8097 9108 1053 5517 1808 9108 8097]]


In [101]:
dim=10

In [102]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [103]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [104]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 96ms/step
[[[-0.02296318 -0.01922374  0.0368497  -0.03579916 -0.0009378
   -0.03761284  0.02785888  0.02983705 -0.02277485 -0.0002177 ]
  [-0.02296318 -0.01922374  0.0368497  -0.03579916 -0.0009378
   -0.03761284  0.02785888  0.02983705 -0.02277485 -0.0002177 ]
  [-0.02296318 -0.01922374  0.0368497  -0.03579916 -0.0009378
   -0.03761284  0.02785888  0.02983705 -0.02277485 -0.0002177 ]
  [-0.02296318 -0.01922374  0.0368497  -0.03579916 -0.0009378
   -0.03761284  0.02785888  0.02983705 -0.02277485 -0.0002177 ]
  [-0.02717313 -0.01367993  0.03351558  0.04539889 -0.0049757
    0.00170362  0.01077425 -0.04993911 -0.00831612  0.0249621 ]
  [-0.04058551  0.01773984 -0.03690742  0.04832703 -0.04553727
   -0.04905515 -0.02146589  0.00246356  0.02924008  0.04383779]
  [ 0.04806777  0.00608522  0.011419    0.04542765  0.01160859
    0.01329298 -0.03490994 -0.0367926   0.04639356 -0.0269212 ]
  [ 0.03850536 -0.02774214 -0.00544488  0.04469278  0.01941908
 

In [105]:
embedded_docs[0]

array([   0,    0,    0,    0, 6911, 8097, 9108, 1053])

In [106]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 27ms/step
[[-0.02296318 -0.01922374  0.0368497  -0.03579916 -0.0009378  -0.03761284
   0.02785888  0.02983705 -0.02277485 -0.0002177 ]
 [-0.02296318 -0.01922374  0.0368497  -0.03579916 -0.0009378  -0.03761284
   0.02785888  0.02983705 -0.02277485 -0.0002177 ]
 [-0.02296318 -0.01922374  0.0368497  -0.03579916 -0.0009378  -0.03761284
   0.02785888  0.02983705 -0.02277485 -0.0002177 ]
 [-0.02296318 -0.01922374  0.0368497  -0.03579916 -0.0009378  -0.03761284
   0.02785888  0.02983705 -0.02277485 -0.0002177 ]
 [-0.02717313 -0.01367993  0.03351558  0.04539889 -0.0049757   0.00170362
   0.01077425 -0.04993911 -0.00831612  0.0249621 ]
 [-0.04058551  0.01773984 -0.03690742  0.04832703 -0.04553727 -0.04905515
  -0.02146589  0.00246356  0.02924008  0.04383779]
 [ 0.04806777  0.00608522  0.011419    0.04542765  0.01160859  0.01329298
  -0.03490994 -0.0367926   0.04639356 -0.0269212 ]
 [ 0.03850536 -0.02774214 -0.00544488  0.04469278  0.01941908  0.04564575

In [107]:
embedded_docs[7]

array([6911, 8097, 9108, 1053, 5517, 1808, 9108, 8097])

In [108]:
print(model.predict(embedded_docs)[7])

1/1 [==============================] - 0s 35ms/step
[[-0.02717313 -0.01367993  0.03351558  0.04539889 -0.0049757   0.00170362
   0.01077425 -0.04993911 -0.00831612  0.0249621 ]
 [-0.04058551  0.01773984 -0.03690742  0.04832703 -0.04553727 -0.04905515
  -0.02146589  0.00246356  0.02924008  0.04383779]
 [ 0.04806777  0.00608522  0.011419    0.04542765  0.01160859  0.01329298
  -0.03490994 -0.0367926   0.04639356 -0.0269212 ]
 [ 0.03850536 -0.02774214 -0.00544488  0.04469278  0.01941908  0.04564575
   0.02616979 -0.04925209  0.00269401  0.04133313]
 [ 0.02664519 -0.01623064 -0.00624384 -0.00644051 -0.01536401  0.01751317
  -0.01705832  0.02500663 -0.01532718  0.00576904]
 [-0.01723846  0.0140697  -0.02275955 -0.03171607  0.01416535 -0.02380655
  -0.02473294 -0.0138059  -0.00709033  0.0023237 ]
 [ 0.04806777  0.00608522  0.011419    0.04542765  0.01160859  0.01329298
  -0.03490994 -0.0367926   0.04639356 -0.0269212 ]
 [-0.04058551  0.01773984 -0.03690742  0.04832703 -0.04553727 -0.04905515

# Word Embedding using gensim

In [109]:
import nltk
from gensim.models import Word2Vec
from nltk.corpus import stopwords
import re

In [140]:
paragraph = '''With pleasure! Let's delve into the fascinating realms of man, woman, king, and queen, exploring their intricate roles, evolving identities, and enduring impact on our world.

Man and Woman: A Tapestry of Duality and Diversity

Man and woman, two fundamental pillars of humanity, intertwined through shared history, yet forever distinguished by biological and social constructs. Their identities are not monolithic, but rather mosaics of individual experiences, cultural expectations, and personal choices.

The Biological Canvas:

Testosterone paints the canvas of masculinity, shaping muscle mass, facial hair, and even vocal pitch. It fuels a drive for competition and achievement, often translated into roles of protector and provider. Estrogen, on the other hand, lays the groundwork for femininity, influencing fertility, maternal instincts, and emotional expression. However, biology is not destiny. Variations in hormone levels and individual responses blur the lines, presenting a spectrum of possibilities rather than rigid binaries.

The Social Script:

Traditional social constructs have assigned specific roles to men and women. Men were expected to be stoic, dominant figures, the breadwinners and decision-makers. Women were seen as nurturing caregivers, primarily responsible for domestic duties and childcare. These rigid expectations often led to limitations and inequalities, stifling individual potential and creating unnecessary conflict.

The Tapestry of Today:

The 21st century witnesses a beautiful unraveling of these outdated scripts. Men are embracing vulnerability and emotional expression, exploring diverse career paths, and actively participating in childcare. Women are shattering glass ceilings in the workplace, leading movements for social justice, and reclaiming their narratives through art, literature, and activism.

King and Queen: Power and Responsibility in Different Garbs

Kings and queens, figures cloaked in history and often adorned with crowns, represent different forms of power and responsibility. Their roles have evolved over time, reflecting changing societal structures and ideals.

The Warrior Kings:

In the dawn of civilization, kings emerged as warrior-leaders, wielding physical strength and strategic prowess to protect their tribes and secure resources. Think Gilgamesh of Mesopotamia or King Leonidas of Sparta, their reigns etched in tales of conquest and unwavering resolve.

The Wise Rulers:

As empires rose and complex societies formed, the role of the king transitioned towards statecraft and diplomacy. Leaders like Ashoka of India or Queen Hatshepsut of Egypt became skilled administrators, fostering trade, promoting art and learning, and laying the foundations for enduring civilizations.

The Modern Landscape:

In the modern world, the concept of monarchy has taken diverse forms. While some countries retain hereditary monarchies, others have opted for elected heads of state or parliamentary systems. Regardless of the system, the essence of leadership – guiding, uniting, and inspiring progress – remains a crucial aspect of governance.

Queens: From Shadows to Spotlights

Queens, often seen as the counterparts to kings, have historically occupied diverse spaces within the power structure. Some, like Catherine de Medici of France, wielded significant political influence in the shadows, acting as advisors and power brokers behind the throne. Others, like Elizabeth I of England, ruled with absolute authority, leaving an indelible mark on their nations' histories.

Beyond the Throne:

Today, the concept of "queen" extends far beyond royal courts. Businesswomen, philanthropists, scientists, and artists are claiming their rightful space as leaders and changemakers. Mothers and mentors are the queens of their households, nurturing and guiding the next generation. The essence of a queen – resilience, wisdom, and the ability to inspire others – has become a powerful symbol of female empowerment in all spheres of life.

Man, Woman, King, Queen: A Collaborative Tapestry

The future of these intertwined identities lies not in rigid definitions or competition, but in collaboration and mutual respect. Men and women can work together to dismantle outdated stereotypes and build a world where everyone thrives. Kings and queens, whether in traditional roles or modern leadership positions, can utilize their power to champion equality, justice, and progress for all.

Ultimately, the stories of man, woman, king, and queen are not separate narratives, but threads woven into a single tapestry of humanity. It is a tapestry constantly evolving, with each generation adding its own unique colors and textures. By embracing diversity, recognizing the strengths of each thread, and collaborating towards a brighter future, we can create a world where every individual flourishes and contributes to a more just and equitable society.

Remember, this is just a starting point. Feel free to explore specific aspects of these identities further, delve into historical figures or contemporary movements, or even share your own thoughts and experiences on what it means to be a man, woman, king,'''

In [141]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ved\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [142]:
# Preprocessing the data
text = re.sub(r'\[[0-9]*\]',' ',paragraph)
text = re.sub(r'\s+',' ',text)
text = text.lower()
text = re.sub(r'\d',' ',text)
text = re.sub(r'\s+',' ',text)

# Preparing the dataset
sentences = nltk.sent_tokenize(text)

sentences = [nltk.word_tokenize(sentence) for sentence in sentences]

for i in range(len(sentences)):
    sentences[i] = [word for word in sentences[i] if word not in stopwords.words('english')]

In [143]:
# Training the Word2Vec model
model = Word2Vec(sentences, min_count=1, vector_size=4)

In [144]:
vector = model.wv['king']

In [145]:
vector

array([ 0.07151555,  0.02366619, -0.20054443, -0.23584826], dtype=float32)

In [146]:
similar = model.wv.most_similar('king')

In [147]:
similar

[('fertility', 0.9742832779884338),
 ('leonidas', 0.9668865203857422),
 ('india', 0.9609314203262329),
 ('opted', 0.9495121240615845),
 ('diplomacy', 0.9278146624565125),
 ('civilizations', 0.9017810225486755),
 ('social', 0.8906058669090271),
 ('collaboration', 0.8883264064788818),
 ('spectrum', 0.8857601881027222),
 ('assigned', 0.8449699878692627)]

In [148]:
king = model.wv['king']
queen = model.wv['queen']
man = model.wv['man']
woman = model.wv['woman']