In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [4]:
x=np.array([2.0, 1.0, 0.1])
outputs = softmax(x)
print('softmax numpy: ', outputs)

softmax numpy:  [0.65900114 0.24243297 0.09856589]


In [5]:
x=torch.tensor([2.0, 1.0, 0.1])
outputs=torch.softmax(x, dim=0)
print('softmax tensor: ', outputs)

softmax tensor:  tensor([0.6590, 0.2424, 0.0986])


In [6]:
def cross_entropy(actual, predicted):
    loss = -np.sum(actual*np.log(predicted))
    return loss

In [7]:
#Y must be one hot encoded
Y = np.array([1,0,0])

In [8]:
#Y_predicted be probability

Y_pred_good = np.array([0.7, 0.2, 0.1])  #Remeber, this is values after applying softmax
Y_pred_bad = np.array([0.1, 0.3, 0.6])  #Remeber, this is values after applying softmax

In [10]:
l1 = cross_entropy(Y, Y_pred_good)
l2 = cross_entropy(Y, Y_pred_bad)

In [11]:
print(f'Loss1 numpy:{l1:.4f}')
print(f'Loss2 numpy:{l2:.4f}')

Loss1 numpy:0.3567
Loss2 numpy:2.3026


In [12]:
#Using Trensor

In [14]:
loss = nn.CrossEntropyLoss()

In [21]:
#1 sample
Y = torch.tensor([0]) #only class label, no one hot encoded needed

#nsamples * n class
Y_pred_good = torch.tensor([[2.0, 1.0, 0.1]])  #REMEBER: this is raw valu, we didn't apply softmax
Y_pred_bad = torch.tensor([[0.5, 2.0, 0.3]])  #REMEBER: this is raw valu, we didn't apply softmax
                                                #Also remember that, this is in double brackertt [[]] (i.e., array of array), however in numpy implementation it was single bracket[]
    

In [22]:
l1=loss(Y_pred_good, Y)
l2=loss(Y_pred_bad, Y)
print(l1.item())
print(l2.item())

0.4170299470424652
1.840616226196289


In [24]:
_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1)
print(predictions1)
print(predictions2)


tensor([0])
tensor([1])


In [25]:
#3 sample
Y = torch.tensor([2,0,1]) #only class label, no one hot encoded needed

#nsamples * n class
Y_pred_good = torch.tensor([[0.1, 1.0, 2.1], [2.0, 1.0, 0.1], [0.1, 3.0, 0.1]])  #REMEBER: this is raw valu, we didn't apply softmax
Y_pred_bad = torch.tensor([[2.1, 1.0, 0.1], [0.1, 1.0, 2.1], [0.1, 3.0, 0.1]])  #REMEBER: this is raw valu, we didn't apply softmax
                                                #Also remember that, this is in double brackertt [[]] (i.e., array of array), however in numpy implementation it was single bracket[]
    

In [26]:
l1=loss(Y_pred_good, Y)
l2=loss(Y_pred_bad, Y)
print(l1.item())
print(l2.item())

0.3018244206905365
1.6241613626480103


In [27]:
_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1)
print(predictions1)
print(predictions2)

tensor([2, 0, 1])
tensor([0, 2, 1])


Note: In pytorch must be carefull that, since we use CrossEntropyLoss hence we must not manually implement softmax layer

Note: But if we use BCELoss() which stands for binary cross entropy loss, then we must use sigmoid at the end