In [1]:
import torch

Creating tensor of empty values

In [2]:
x=torch.empty(1)

In [3]:
print(x)

tensor([0.])


In [4]:
x=torch.empty(3)

In [5]:
print(x)

tensor([0., 0., 0.])


In [6]:
x=torch.empty(2,3)

In [7]:
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
x=torch.empty(2,3,3)

In [9]:
print(x)

tensor([[[-8.1353e-31,  1.7558e-42,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])


In [10]:
x=torch.empty(2,2,3,3)

In [11]:
print(x)

tensor([[[[-8.1970e-31,  1.7558e-42,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]]])


Creating tensor of random values

In [12]:
x=torch.rand(2,2)

In [13]:
print(x)

tensor([[0.1573, 0.7667],
        [0.1023, 0.5799]])


Creating tensor of zeros

In [14]:
x=torch.zeros(2,2)

In [15]:
print(x)

tensor([[0., 0.],
        [0., 0.]])


creating tensor of ones

In [16]:
x=torch.ones(2,2)

In [17]:
print(x)

tensor([[1., 1.],
        [1., 1.]])


checking data type

In [18]:
print(x.dtype)

torch.float32


defualt datatype is torch.float32, however, at the time of initialization, explicitly datatype can be mentioned

In [19]:
x=torch.ones(2,2,dtype=int)

In [20]:
print(x)

tensor([[1, 1],
        [1, 1]])


In [21]:
print(x.dtype)

torch.int64


Checking size of tensor

In [22]:
print(x.size())

torch.Size([2, 2])


craeting tensor with values

In [23]:
x=torch.tensor([1.2,5.3])

In [24]:
print(x)

tensor([1.2000, 5.3000])


# Basic operations on tensor

In [25]:
x=torch.rand(2,2)
y=torch.rand(2,2)

In [26]:
print(x)
print(y)

tensor([[0.0362, 0.5448],
        [0.7214, 0.7905]])
tensor([[0.6445, 0.9294],
        [0.2557, 0.4762]])


In [27]:
z=x+y
print(z)

tensor([[0.6807, 1.4743],
        [0.9771, 1.2667]])


In [28]:
z=torch.add(x,y)
print(z)

tensor([[0.6807, 1.4743],
        [0.9771, 1.2667]])


inplace addition

In [29]:
y.add_(x)

tensor([[0.6807, 1.4743],
        [0.9771, 1.2667]])

Note: In Pytorch, the function with trailing "_" does inplace operation

In [30]:
print(y)

tensor([[0.6807, 1.4743],
        [0.9771, 1.2667]])


In [34]:
z=x-y
print(z)

tensor([[-0.6445, -0.9294],
        [-0.2557, -0.4762]])


In [35]:
z=torch.sub(x,y)
print(z)

tensor([[-0.6445, -0.9294],
        [-0.2557, -0.4762]])


In [36]:
z=x*y
print(z)

tensor([[0.0247, 0.8032],
        [0.7049, 1.0014]])


In [37]:
z=torch.mul(x,y)
print(z)

tensor([[0.0247, 0.8032],
        [0.7049, 1.0014]])


In [38]:
z = x/y
print(z)

tensor([[0.0532, 0.3696],
        [0.7383, 0.6240]])


In [39]:
z = torch.div(x,y)
print(z)

tensor([[0.0532, 0.3696],
        [0.7383, 0.6240]])


# Slicing Operations

In [41]:
x=torch.rand(5,3)
print(x)

tensor([[0.5740, 0.2334, 0.9050],
        [0.1562, 0.6933, 0.0965],
        [0.7046, 0.1343, 0.7489],
        [0.9230, 0.3915, 0.5745],
        [0.2525, 0.6711, 0.9972]])


In [42]:
#Select all rows but only first column
print(x[:,0])

tensor([0.5740, 0.1562, 0.7046, 0.9230, 0.2525])


In [44]:
#Select first row and all column
print(x[0,:])

tensor([0.5740, 0.2334, 0.9050])


In [48]:
#Selecting single element of tensor
print(x[1,1])

#to get actual value, function item() is used
#Please note that, item() works on only single value

print(x[1,1].item())

tensor(0.6933)
0.6933351755142212


# Reshaping the tensor

In [50]:
x=torch.rand(4,4)
print(x)

tensor([[0.6805, 0.8083, 0.0731, 0.1692],
        [0.2103, 0.5523, 0.1910, 0.0973],
        [0.4956, 0.9322, 0.9948, 0.3490],
        [0.0410, 0.0759, 0.5110, 0.4777]])


In [51]:
y=x.view(16)
print(y)

tensor([0.6805, 0.8083, 0.0731, 0.1692, 0.2103, 0.5523, 0.1910, 0.0973, 0.4956,
        0.9322, 0.9948, 0.3490, 0.0410, 0.0759, 0.5110, 0.4777])


In [52]:
y=x.view(-1,8)
print(y)

tensor([[0.6805, 0.8083, 0.0731, 0.1692, 0.2103, 0.5523, 0.1910, 0.0973],
        [0.4956, 0.9322, 0.9948, 0.3490, 0.0410, 0.0759, 0.5110, 0.4777]])


In [53]:
y=x.view(-1,4)
print(y)

tensor([[0.6805, 0.8083, 0.0731, 0.1692],
        [0.2103, 0.5523, 0.1910, 0.0973],
        [0.4956, 0.9322, 0.9948, 0.3490],
        [0.0410, 0.0759, 0.5110, 0.4777]])


In [54]:
y=x.view(-1,5)
print(y)

RuntimeError: shape '[-1, 5]' is invalid for input of size 16

# Converting from tensor to numpy 

In [55]:
import numpy as np

In [57]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [58]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [59]:
print(type(b))

<class 'numpy.ndarray'>


Note: on cpu, both object share same memory location


In [60]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [61]:
print(b)

[2. 2. 2. 2. 2.]


# Converting from numpy to tensor

In [63]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [64]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Note: on cpu, both object share same memory location

In [66]:
a += 1
print(a)

[2. 2. 2. 2. 2.]


In [67]:
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# On gpu

In [68]:
torch.cuda.is_available()

False

In [70]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    z = x+y
    
    #numpy can only handle cpu tensor, not gpu sensor
    #z.numpy()
    
    #We need to move it to cpu in order to use numpy()
    z=z.to("cpu")
    z.numpy()
    

# requires_grad

In [72]:
x=torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
