In [5]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [6]:
##!pip install torchvision

In [11]:
class WineDataset(Dataset):
    def __init__(self):
        #data loading
        xy = np.loadtxt('wine.csv', delimiter=",", dtype=np.float32, skiprows=1)
        self.x = torch.from_numpy(xy[:,1:])
        self.y = torch.from_numpy(xy[:,[0]])
        self.n_samples = xy.shape[0]
    def __getitem__(self, index):
        #dataset[0]
        return self.x[index], self.y[index]
    
    def __len__(self):
        #len(dataset)
        return self.n_samples
        
    

In [12]:
dataset = WineDataset()

In [15]:
first_data = dataset[0]

In [17]:
features, labels = first_data

In [20]:
print(features)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])


In [21]:
print(labels)

tensor([1.])


In [28]:
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True, num_workers=2)

In [29]:
dataiter = iter(dataloader)

In [34]:
#data = dataiter.next()
data = next(dataiter)

In [35]:
features, labels = data

In [37]:
print(features, labels)

tensor([[1.2510e+01, 1.7300e+00, 1.9800e+00, 2.0500e+01, 8.5000e+01, 2.2000e+00,
         1.9200e+00, 3.2000e-01, 1.4800e+00, 2.9400e+00, 1.0400e+00, 3.5700e+00,
         6.7200e+02],
        [1.3230e+01, 3.3000e+00, 2.2800e+00, 1.8500e+01, 9.8000e+01, 1.8000e+00,
         8.3000e-01, 6.1000e-01, 1.8700e+00, 1.0520e+01, 5.6000e-01, 1.5100e+00,
         6.7500e+02],
        [1.3730e+01, 1.5000e+00, 2.7000e+00, 2.2500e+01, 1.0100e+02, 3.0000e+00,
         3.2500e+00, 2.9000e-01, 2.3800e+00, 5.7000e+00, 1.1900e+00, 2.7100e+00,
         1.2850e+03],
        [1.2580e+01, 1.2900e+00, 2.1000e+00, 2.0000e+01, 1.0300e+02, 1.4800e+00,
         5.8000e-01, 5.3000e-01, 1.4000e+00, 7.6000e+00, 5.8000e-01, 1.5500e+00,
         6.4000e+02]]) tensor([[2.],
        [3.],
        [1.],
        [3.]])


In [40]:
#training loop
num_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4)


In [42]:
print(total_samples, n_iterations)

178 45


In [47]:
for  epoch in range(num_epochs):
    for i, (inputs, labels) in enumerate(dataloader):
        #forward, backward, update
        if(i+1)%5==0:
            print(f'epoch {epoch+1}/{num_epochs}, step{i+1}/{n_iterations}, inputs {inputs.shape}')

epoch 1/2, step5/45, inputs torch.Size([4, 13])
epoch 1/2, step10/45, inputs torch.Size([4, 13])
epoch 1/2, step15/45, inputs torch.Size([4, 13])
epoch 1/2, step20/45, inputs torch.Size([4, 13])
epoch 1/2, step25/45, inputs torch.Size([4, 13])
epoch 1/2, step30/45, inputs torch.Size([4, 13])
epoch 1/2, step35/45, inputs torch.Size([4, 13])
epoch 1/2, step40/45, inputs torch.Size([4, 13])
epoch 1/2, step45/45, inputs torch.Size([2, 13])
epoch 2/2, step5/45, inputs torch.Size([4, 13])
epoch 2/2, step10/45, inputs torch.Size([4, 13])
epoch 2/2, step15/45, inputs torch.Size([4, 13])
epoch 2/2, step20/45, inputs torch.Size([4, 13])
epoch 2/2, step25/45, inputs torch.Size([4, 13])
epoch 2/2, step30/45, inputs torch.Size([4, 13])
epoch 2/2, step35/45, inputs torch.Size([4, 13])
epoch 2/2, step40/45, inputs torch.Size([4, 13])
epoch 2/2, step45/45, inputs torch.Size([2, 13])
